#!/bin/sh /etc/rc.common

START=99
STOP=15

start() {
   echo "Starting anylink"
  /usr/share/AnyLink/anylink --conf=/usr/share/AnyLink/conf/server.toml &
}

stop() {
   killall anylink
   echo "Kill anylink"
}

restart() {
  echo "Restarting anylink"
  /etc/init.d/anylink stop
  /etc/init.d/anylink start
}